- the bot crashes when a new Mod is added with the following error...why?!?
/Users/adamr/Documents/Git/DaManagement/modules/moderatorModule.js:10
        if (this.modList.indexOf(data.userid) === -1)
                                      ^

TypeError: Cannot read property 'userid' of undefined
    at Object.newModerator (/Users/adamr/Documents/Git/DaManagement/modules/moderatorModule.js:10:39)
    at Bot.<anonymous> (/Users/adamr/Documents/Git/DaManagement/DaManagement.js:4808:21)
    at Bot.emit (node:events:378:20)
    at Bot.treatCommand (/Users/adamr/Documents/Git/DaManagement/node_modules/ttapi/src/bot.js:319:17)
    at Bot.treatPacket (/Users/adamr/Documents/Git/DaManagement/node_modules/ttapi/src/bot.js:326:17)
    at Bot.onMessage (/Users/adamr/Documents/Git/DaManagement/node_modules/ttapi/src/bot.js:336:17)
    at WebSocket.<anonymous> (/Users/adamr/Documents/Git/DaManagement/node_modules/ttapi/src/bot.js:110:21)
    at WebSocket.emit (node:events:378:20)
    at Receiver.receiverOnMessage (/Users/adamr/Documents/Git/DaManagement/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (node:events:378:20)