- changed a bunch but now getting this error which is odd, because the missing functions it's complaining about does exist?!?
commandModule.js:723

bot.speak('Hey! How are you @' + userFunctions.name() + '?');

TypeError: userFunctions.name is not a function